# CPPFLAGS = -Wall -std=c++14 -g
# pet.hpp pet.cpp 

all:
	g++ main.cpp pet.cpp controller.cpp -o main
	.\main

c:
	g++ main.cpp pet.cpp controller.cpp -c

o:
	g++ main.o pet.o controller.o -o main

clean:
	rm -rf main.exe